name: web_socket_rev
description: "Any easy-to-use library for communicating with WebSockets
  that has multiple channels."
repository: https://github.com/JITHIN665/web_socket_rev.git


version: 1.0.1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true